import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MenuHeader from "@/components/home/header";
import Footer from "@/components/home/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Verzel - Compra e Venda de Carros Seminovos e Usados | Revendedores de Carros",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <MenuHeader/>
        {children}
        <Footer />
        </body>
    </html>
  );
}
